### PR TITLE
feat: integrate vega embed to use tooltip, bug fixes for storybook

### LINKED ISSUE #26: Use Vega-Embed

### PR DESCRIPTION
**Pull request by hungngo97**
Integrate Vega Embed in Vega components to use embedded tooltip. Configure Storybook with new import from react-scripts to read files from local directories.

Fixes #26

### CODE REVIEW

**Comment by ifokeev** [comment]
need vega embed =\

File: packages/react-vega/src/Vega.jsx [hunk 1]
```diff
@@ -5,6 +5,7 @@ import * as vega from 'vega';
 import PropTypes from 'prop-types';
 import React from 'react';
 import { capitalize, isDefined, isFunction } from './util';
+import * as vegaEmbed from 'vega-embed';
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: Do we need `import *` or can it be more specific import?

File: stories/ReactVegaLiteDemo.jsx [hunk 2]
```diff
@@ -70,7 +72,7 @@ export default class Demo extends React.Component {
 
   handleHover(...args) {
     this.setState({
-      info: JSON.stringify(args),
+      info: JSON.stringify(args)
```
Comment (kristw) [inline stories/ReactVegaLiteDemo.jsx]: `yarn lint:fix`

Comment (kristw) [reply stories/ReactVegaLiteDemo.jsx]: Seems like the whole file has been reformatted with double quote and different `eslint` rule.

File: packages/react-vega/src/Vega.jsx [hunk 3]
```diff
@@ -116,15 +117,31 @@ class Vega extends React.Component {
     this.clearView();
   }
 
-  createView(spec) {
+  async createView2(spec) {
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: When is this function being used? If not, please remove.

File: package.json [hunk 4]
```diff
@@ -10,24 +10,26 @@
   },
   "private": true,
   "dependencies": {
-    "react": "^16.8.6"
+    "react": "^16.8.6",
+    "vega-embed": "^4.0.0"
```
Comment (kristw) [inline package.json]: This probably should go into the package specific `package.json` as `peerDependencies` and `devDependencies` in the root `package.json`.

File: packages/react-vega/src/Vega.jsx [hunk 5]
```diff
@@ -116,15 +117,31 @@ class Vega extends React.Component {
...
-        const view = new vega.View(runtime).initialize(this.element);
-
-        // Attach listeners onto the signals
+        const specJson = JSON.stringify(spec);
+        const view = {};
+        try {
+          result = await vegaEmbed.default(this.element, spec);
+          view = result.view;
+        } catch (error) {
+          console.log(error);
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: If creating `view` was not successful. The rest of the code in this function (setting signals, etc.) should not continue.

File: packages/react-vega/src/Vega.jsx [hunk 6]
```diff
@@ -116,15 +117,31 @@ class Vega extends React.Component {
...
     if (spec) {
       const { props } = this;
       // Parse the vega spec and create the view
       try {
-        const runtime = vega.parse(spec);
-        const view = new vega.View(runtime).initialize(this.element);
-
-        // Attach listeners onto the signals
+        const specJson = JSON.stringify(spec);
+        const view = {};
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: `let view;` because you are about to modify the value after.

**Comment by kristw** [comment]
Thank you for your contribution!

**Comment by kanitw** [comment]
Right now many properties (`['logLevel', 'renderer', 'tooltip', 'background', 'width', 'height', 'padding']`) are still relying on the view to set the values.  

However, given Vega Embed already provide most (if not all) of these properties in [the option](https://github.com/vega/vega-embed#options), it might be better to 

1) just use those properties 
2) include other vega-embed options as properties of the React Vega Component?

(I guess 2. makes sense, but let's see what @domoritz and @kristw say)

**Comment by kanitw** [comment]
@kristw  -- please let @hungngo97 if you prefer to have the refactor to use vega-embed options in this PR or in a separate PR.

**Comment by kristw** [comment]
@kanitw Let's do that in a separate PR. I would limit the scope of this PR to ensure feature parity and not changing API, so it will be decent size for reviewing.

**Comment by domoritz** [comment]
@hungngo97 cand you finish this PR?

**Comment by hungngo97** [comment]
Just fixed !:)

**Comment by domoritz** [comment]
Thank you. @kristw can you have a look?

**Comment by domoritz** [comment]
Thank you. Will try to have a look soon.

File: packages/react-vega/src/Vega.jsx [hunk 7]
```diff
@@ -116,15 +116,22 @@ class Vega extends React.Component {
...
       // Parse the vega spec and create the view
       try {
-        const runtime = vega.parse(spec);
-        const view = new vega.View(runtime).initialize(this.element);
-
-        // Attach listeners onto the signals
+        const specJson = JSON.stringify(spec);
+        let view = {};
+        try {
+          console.log(vegaEmbed);
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: remove `console.log`

**Comment by kristw** [comment]
Hi @hungngo97 , several of my comments are still not addressed though.

**Comment by domoritz** [comment]
@hungngo97 ping me when this is ready

File: packages/react-vega/src/Vega.jsx [hunk 8]
```diff
@@ -1,9 +1,11 @@
+/* eslint-disable no-undef */
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: Why is this disabled?

File: packages/react-vega/src/Vega.jsx [hunk 9]
```diff
@@ -114,15 +116,18 @@ class Vega extends React.Component {
...
-        const runtime = vega.parse(spec);
-        const view = new vega.View(runtime).initialize(this.element);
-
-        // Attach listeners onto the signals
+        let view = {};
+        try {
+          result = await vegaEmbed(this.element, spec);
+          ({ view } = result);
+        } catch (error) {
+          throw new Error('Something went wrong parsing Vega specs');
```
Comment (kristw) [inline packages/react-vega/src/Vega.jsx]: What is the benefit of catching to rethrow and ignoring the original error message?

File: packages/react-vega-lite/package.json [hunk 10]
```diff
@@ -18,14 +18,18 @@
...
-    "react-vega": "^6.0.1"
+    "react-vega": "^6.0.1",
+    "vega-embed": "^4.0.0"
   },
   "peerDependencies": {
     "react": "^16.0.0",
     "vega-lite": "^3.1.0"
   },
+  "devDependencies": {
+    "vega-lite": "^3.1.0"
```
Comment (kristw) [inline packages/react-vega-lite/package.json]: not necessary because this is already in the `devDependencies` of root `package.json` so when you `yarn install`, this monorepo will have `vega-lite` for development

File: packages/react-vega-lite/package.json [hunk 11]
```diff
@@ -18,14 +18,18 @@
     "types"
   ],
   "dependencies": {
-    "react-vega": "^6.0.1"
+    "react-vega": "^6.0.1",
+    "vega-embed": "^4.0.0"
   },
   "peerDependencies": {
     "react": "^16.0.0",
     "vega-lite": "^3.1.0"
```
Comment (kristw) [inline packages/react-vega-lite/package.json]: this is redundant because `vega-lite` is already `peerDependencies` of `vega-embed`

File: packages/react-vega/package.json [hunk 12]
```diff
@@ -18,14 +18,18 @@
     "types"
   ],
   "dependencies": {
-    "prop-types": "^15.7.2"
+    "prop-types": "^15.7.2",
+    "vega-embed": "^4.0.0"
   },
   "peerDependencies": {
     "react": "^16.0.0",
     "vega": "^5.3.4"
```
Comment (kristw) [inline packages/react-vega/package.json]: this is redundant because `vega` is already `peerDependencies` of `vega-embed`

File: packages/react-vega/package.json [hunk 13]
```diff
@@ -18,14 +18,18 @@
...
   },
+  "devDependencies": {
+    "vega": "^5.3.4"
```
Comment (kristw) [inline packages/react-vega/package.json]: not necessary because this is already in the root `package.json` so when you `yarn install` this monorepo will have `vega` for development

File: packages/react-vega-lite/package.json [hunk 14]
```diff
@@ -25,8 +25,12 @@
     "vega-lite": "^3.1.0",
     "vega-embed": "^4.0.0"
```
Comment (domoritz) [inline packages/react-vega-lite/package.json]: I think vega embed should be a dependency, not a peer dependency

File: packages/react-vega/src/Vega.jsx (hunk 9 above)
Comment (domoritz) [reply packages/react-vega/src/Vega.jsx]: I agree. Let's just remove this and let people take care of handing errors.

File: packages/react-vega/src/Vega.jsx [hunk 15]
```diff
@@ -119,16 +121,12 @@ class Vega extends React.Component {
...
       // Parse the vega spec and create the view
       try {
-        const specJson = JSON.stringify(spec);
         let view = {};
         try {
-          console.log(vegaEmbed);
           result = await vegaEmbed(this.element, spec);
-          // result = await embed(this.element, spec);
-          view = result.view;
+          ({ view } = result);
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: You can combine these two lines, no?

File: packages/react-vega/src/Vega.jsx [hunk 16]
```diff
@@ -119,16 +121,12 @@ class Vega extends React.Component {
       const { props } = this;
       // Parse the vega spec and create the view
       try {
-        const specJson = JSON.stringify(spec);
         let view = {};
         try {
-          console.log(vegaEmbed);
           result = await vegaEmbed(this.element, spec);
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: The reason we want to use embed is that we can use the embed options. This is missing in this PR. Can you add it?

Comment (kanitw) [reply packages/react-vega/src/Vega.jsx]: Hmm perhaps do that in another PR -- see https://github.com/vega/react-vega/pull/38#issuecomment-495728470.

Comment (domoritz) [reply packages/react-vega/src/Vega.jsx]: Okay, but we should at least pass properties to embed instead of duplicating implementations.

File: packages/react-vega/src/Vega.jsx [hunk 17]
```diff
@@ -4,12 +4,14 @@ import * as vega from 'vega';
...
 import PropTypes from 'prop-types';
 import React from 'react';
+import vegaEmbed from 'vega-embed';
 import { capitalize, isDefined, isFunction } from './util';
 
 const propTypes = {
   background: PropTypes.string,
   className: PropTypes.string,
   data: PropTypes.object,
+  embedOption: PropTypes.object,
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: Let's not add this yet and instead just redirect the existing options as suggested in another comment.

File: packages/react-vega/src/Vega.jsx [hunk 18]
```diff
@@ -183,6 +160,23 @@ class Vega extends React.Component {
...
+        if (field === 'enableHover') {
+          // Since declared type of react vega is enableHover while
+          // vega-embed use hover
+          embedOptionClone.hover = props[field];
+        } else {
+          embedOptionClone[field] = props[field];
+        }
+      });
+
+    return embedOptionClone;
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: A cleaner way is

```
options = {
   	...embedOptions,
	renderer ? {renderer} : {},
	[...]
}
```

It also ensures type safety.

File: stories/ReactVegaDemo.jsx [hunk 19]
```diff
@@ -27,6 +29,7 @@ export default class Demo extends React.Component {
   }
 
   handleHover(...args) {
+    console.log('YOOOOOOO');
```
Comment (domoritz) [inline stories/ReactVegaDemo.jsx]: What this?

File: packages/react-vega/src/Vega.jsx [hunk 20]
```diff
@@ -160,21 +154,18 @@ class Vega extends React.Component {
...
-          embedOptionClone.hover = props[field];
-        } else {
-          embedOptionClone[field] = props[field];
-        }
-      });
-
-    return embedOptionClone;
+  propsToEmbedOption(props) {
+    const options = {
+      enableHover: props.enableHover ? props.enableHover : true,
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: Change this to `...props.enableHover ? {enableHover: props.enableHover},` as I suggested. The way you wrote it, you have to repeat the defaults.

Comment (hungngo97) [reply packages/react-vega/src/Vega.jsx]: `    const options = {
      ...props.enableHover,
      ...props.height,
      ...props.logLevel,
      ...props.padding,
      ...props.renderer,
      ...props.tooltip,
      ...props.width,
    };`

Since these props we ensure it to have the default value, can I just directly spread it without the conditional?

Comment (domoritz) [reply packages/react-vega/src/Vega.jsx]: But you are repeating the defaults and if they change in embed, you also have to change them here, no? This could be the right thing if we want to keep different defaults in react vega. Do you think we want that?

File: packages/react-vega/src/Vega.jsx [hunk 21]
```diff
@@ -183,6 +154,20 @@ class Vega extends React.Component {
     }
   }
 
+  propsToEmbedOption(props) {
+    const options = {
+      ...(props.enableHover ? { enableHover: props.enableHover } : {}),
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: It's called just `hover` in Vega-Embed.

Comment (domoritz) [reply packages/react-vega/src/Vega.jsx]: We should switch to typescript at some point soon to catch these errors.

File: packages/react-vega/src/Vega.jsx [hunk 22]
```diff
@@ -74,19 +75,6 @@ class Vega extends React.Component {
       const { props } = this;
       let changed = false;
 
-      // update view properties
-      ['width', 'height', 'renderer', 'logLevel', 'background']
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: Where did all of this functionality go?

File: packages/react-vega/src/Vega.jsx [hunk 23]
```diff
@@ -99,11 +87,6 @@ class Vega extends React.Component {
         });
       }
 
-      if (!prevProps.enableHover && props.enableHover) {
-        this.view.hover();
```
Comment (domoritz) [inline packages/react-vega/src/Vega.jsx]: and this?

File: packages/react-vega/package.json [hunk 24]
```diff
@@ -28,4 +29,4 @@
   "publishConfig": {
     "access": "public"
   }
-}
+}
```
Comment (domoritz) [inline packages/react-vega/package.json]: We usually keep an empty line at the end of files.

File: stories/ReactVegaLiteDemo.jsx [hunk 25]
```diff
@@ -1,5 +1,5 @@
 import React from 'react';
-import VegaLite, { createClassFromLiteSpec } from '../packages/react-vega-lite';
+import VegaLite, { createClassFromLiteSpec } from '../packages/react-vega-lite/src';
```
Comment (domoritz) [inline stories/ReactVegaLiteDemo.jsx]: We shouldn't do this. We should use the actual package.

**Comment by crispamares** [comment]
I wonder what are the gains/regresions of including `react-embed` in this project appart from having the actions that `react-embed` provides.

I use this library in production to include in our React app lots of interactive visualizations. (Thanks for the job by the way ^_^). I don't know how people are using this library, in my project we will just hide all the controls that `react-embed` provides..., that is why I ask for other implications.

Particularly, do you expect any performance change?

**Comment by domoritz** [comment]
Good question. Vega-Embed (I suppose you don't mean `react-embed`, right?) is a thin wrapper and there should be no performance implications. However, if you want to hide all the action buttons, we should make it very easy for you to do so. How do you hide the action buttons now?

**Comment by crispamares** [comment]
Yes `vega-embed` 🙈 

I am not hiding anything, we are still using a previous version of `react-vega` (previous of having `vega-embed` as dependency)

File: packages/react-vega/src/Vega.jsx (hunk 17 above)
Comment (crubier) [reply packages/react-vega/src/Vega.jsx]: Just coming to say that in my opinion this was a bad decision. Disabling this escape hatch mean that as a user of the library, I have no way of easily disable the vega-embed action button, which iI don't want.
